App\Entity\Feedback\PollOption:
  properties:
    id:
      identifier: false
    uuid:
      identifier: true
  attributes:
    normalization_context:
      groups: ['pollOption:read']
    denormalization_context:
      groups: ['pollOption:write']
    route_prefix: /feedback/discussions/polls

  collectionOperations:
    post:
      validation_groups: [Default, create]
      openapi_context: 
        tags: [Feedback]
    get:
      method: GET
      openapi_context:
        tags: [Feedback]

  itemOperations:
    get:
      access_control: "object == user"
      openapi_context:
        tags: [Feedback]
    patch:
      access_control: "object == user"
      openapi_context:
        tags: [Feedback]
    delete: 
      access_control: "object == user"
      openapi_context:
        tags: [Feedback]
