App\DTO\Security\ForgotPasswordConfirm:

  itemOperations: {}
  collectionOperations:
    forgot_password_request:
      path: /forgot_password/confirm
      method: POST
      validation_groups: [Default]
      output: false
      swagger_context:
        tags: [Authentication]
        summary: Confirm forgoten password request
