App\DTO\Security\ForgotPasswordRequest:
  properties:
    email:
      identifier: true

  itemOperations: {}
  collectionOperations:
    forgot_password_request:
      path: /forgot_password/request
      method: POST
      validation_groups: [Default]
      output: false
      swagger_context:
        tags: [Authentication]
        summary: Request forgoton password
